
path=('/opt/homebrew/bin' '/opt/homebrew/sbin' $path)

# Add .NET Core SDK tools
path+=('/Users/aschott/.dotnet/tools')

path+=('/Users/aschott/.docker/bin')

export PATH

autoload -Uz compinit; compinit
autoload -U colors && colors

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

# Load Angular CLI autocompletion.
source <(ng completion script)

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/aschott/.docker/completions $fpath)

# Prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/\1/p'
}

NEWLINE=$'\n'
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats "(%b)"
zstyle ':vcs_info:git*' actionformats "(%b)"
precmd() { vcs_info }
PROMPT='%F{#00ff00}[%t] %F{#ffff00}%1~ %F{#00bfff}${vcs_info_msg_0_}%F{#ffffff}${NEWLINE}$ ' 
